#!/usr/bin/env node
// Regenerates AWARDS.md (full index grouped by venue and year) and the
// STATS section of README.md, from data/awards.json.
'use strict';

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const data = JSON.parse(fs.readFileSync(path.join(root, 'data', 'awards.json'), 'utf8'));

const awards = data.awards;
const years = [...new Set(awards.map((a) => a.year))].sort();
const venueNames = [...new Set(awards.map((a) => a.venue))].sort();
const longName = Object.fromEntries((data.venues || []).map((v) => [v.name, v.long]));
const venueLink = Object.fromEntries((data.venues || []).map((v) => [v.name, v.link]));

const anchor = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/* ---------- AWARDS.md ---------- */
const out = [];
out.push('# Social Computing & HCI Best Paper Awards — full index');
out.push('');
out.push(`_${awards.length} awards · ${venueNames.length} venues · ${years[0]}–${years[years.length - 1]} · last updated **${data.lastUpdated}**._`);
out.push('');
out.push(`_Generated from [\`data/awards.json\`](data/awards.json); browsable version at [casp.jp/social-computing-best-papers](${data.url})._`);
out.push('');
out.push('## Venues');
out.push('');
for (const v of venueNames) {
  const n = awards.filter((a) => a.venue === v).length;
  out.push(`- [${v}](#${anchor(v)}) — ${longName[v] || ''} (${n})`);
}
for (const v of venueNames) {
  out.push('');
  out.push(`## ${v}`);
  if (longName[v]) out.push(`_${longName[v]}_${venueLink[v] ? ` · [venue site](${venueLink[v]})` : ''}`);
  const byYear = awards.filter((a) => a.venue === v);
  const vYears = [...new Set(byYear.map((a) => a.year))].sort((a, b) => b - a);
  for (const y of vYears) {
    out.push('');
    out.push(`### ${v} ${y}`);
    out.push('');
    for (const a of byYear.filter((x) => x.year === y)) {
      const title = a.link ? `[${a.title}](${a.link})` : a.title;
      const src = a.source && a.source !== a.link ? ` ([source](${String(a.source).split(/[;,\s]+/)[0]}))` : '';
      out.push(`- **${a.award}** — ${title} — ${a.author}${src}`);
    }
  }
}
out.push('');
fs.writeFileSync(path.join(root, 'AWARDS.md'), out.join('\n'));

/* ---------- README stats ---------- */
const perVenue = venueNames
  .map((v) => `| [${v}](AWARDS.md#${anchor(v)}) | ${longName[v] || ''} | ${awards.filter((a) => a.venue === v).length} |`)
  .join('\n');

const stats = [
  '<!-- STATS:START — auto-generated by tools/build-readme.js from data/awards.json; do not edit by hand -->',
  '## Coverage',
  '',
  `_${awards.length} awards · ${venueNames.length} venues · ${years[0]}–${years[years.length - 1]} · last updated **${data.lastUpdated}**._`,
  '',
  '| Venue | Full name | Awards |',
  '|---|---|---|',
  perVenue,
  '<!-- STATS:END -->',
].join('\n');

const readmePath = path.join(root, 'README.md');
const readme = fs.readFileSync(readmePath, 'utf8');
fs.writeFileSync(readmePath, readme.replace(/<!-- STATS:START[\s\S]*?<!-- STATS:END -->/, stats));
console.log(`AWARDS.md: ${awards.length} awards, ${venueNames.length} venues; README stats updated (dataset ${data.lastUpdated})`);
